[workspace]
members = ["quiver-core", "quiver-compiler", "quiver-cli", "quiver-tests", "quiver-web"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
