[package]
name = "quiver"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "quiv"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.46", features = ["derive"] }
hex = "0.4.3"
pest = "2.8.1"
pest_derive = "2.8.1"
rustyline = "17.0.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
