[package]
name = "quiver-web"
version.workspace = true
edition.workspace = true
description = "WebAssembly runtime for the Quiver programming language"
license = "MIT"
repository = "https://github.com/yourusername/quiver"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
quiver-core = { path = "../quiver-core" }
quiver-compiler = { path = "../quiver-compiler" }

wasm-bindgen = "0.2"
serde.workspace = true
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
console_error_panic_hook = "0.1"
hex = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
]

[profile.release]
opt-level = "s"
lto = true
