//! Emits two things.
//!
//! `QUIVER_COMPILER_FINGERPRINT`: a hash of the sources that determine the compiler's
//! behaviour — this crate and quiver-core. It is one component of every artifact key
//! (see `src/artifact.rs`), so a compiler change invalidates all cached artifacts.
//! Standard-library sources are deliberately *not* hashed: std modules are
//! content-addressed individually through their own sources, so editing one invalidates
//! only its artifact and its dependents' — not every cache on the machine.
//!
//! `std_sources.rs`: the embedded standard library, which `src/resolver.rs` includes.
//! Only the `.qv` modules are embedded — `std/docs/` is prose that `quiv test` reads from
//! the filesystem, and embedding it would put ~180 KB of dead weight in every binary and
//! in the wasm bundle.

use std::collections::hash_map::DefaultHasher;
use std::fmt::Write as _;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

fn main() {
    let mut hasher = DefaultHasher::new();
    for dir in ["src", "../quiver-core/src"] {
        hash_dir(Path::new(dir), Path::new(dir), &mut hasher);
        println!("cargo:rerun-if-changed={dir}");
    }
    println!(
        "cargo:rustc-env=QUIVER_COMPILER_FINGERPRINT={:016x}",
        hasher.finish()
    );

    emit_std_sources();
}

fn hash_dir(root: &Path, dir: &Path, hasher: &mut DefaultHasher) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| entry.expect("cannot read dir entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            hash_dir(root, &path, hasher);
        } else {
            path.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .hash(hasher);
            std::fs::read(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
                .hash(hasher);
        }
    }
}

/// Write `$OUT_DIR/std_sources.rs`: the `.qv` modules under `../std`, as `(path, source)`
/// pairs sorted by path. The generated `include_str!`s give rustc per-file dependency
/// tracking; the directory rerun directive catches modules being added and removed.
fn emit_std_sources() {
    println!("cargo:rerun-if-changed=../std");

    let root = std::fs::canonicalize("../std").expect("cannot locate the standard library");
    let mut modules = Vec::new();
    collect_modules(&root, &root, &mut modules);
    modules.sort();

    let mut out = String::from(
        "/// The standard library: each module's path relative to `std/`, paired with its\n\
         /// source, sorted by path. Generated by `build.rs`.\n\
         static STD_SOURCES: &[(&str, &str)] = &[\n",
    );
    for relative in &modules {
        let absolute = root.join(relative);
        writeln!(
            out,
            "    ({relative:?}, include_str!({:?})),",
            absolute.to_string_lossy()
        )
        .unwrap();
    }
    out.push_str("];\n");

    let path = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("std_sources.rs");
    std::fs::write(&path, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
}

/// Collect the `.qv` files under `dir` as paths relative to `root`.
fn collect_modules(root: &Path, dir: &Path, modules: &mut Vec<String>) {
    for entry in
        std::fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
    {
        let path = entry.expect("cannot read dir entry").path();
        if path.is_dir() {
            collect_modules(root, &path, modules);
        } else if path.extension().is_some_and(|extension| extension == "qv") {
            modules.push(
                path.strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .into_owned(),
            );
        }
    }
}
