[package]
name = "quiver-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "quiver"
path = "src/main.rs"

[dependencies]
quiver-core = { path = "../quiver-core" }
quiver-compiler = { path = "../quiver-compiler" }
quiver-environment = { path = "../quiver-environment" }
